### ISSUE TITLE
after adding sst to the project, cannot run build

### ISSUE THREAD

**Issue by lschierer** [onwidget/astrowind#152]
after running 
```
npx create-sst
```
per https://docs.astro.build/en/guides/deploy/sst/ 
I accepted all default answers and then attempted to run
``
npm run build
```

I get the following error:
```
officium:EvonyTips_v2 luke$ npm run build

> @onwidget/astrowind@0.9.8 build
> astro build

01:55:45 PM [content] Unsupported file types found. Prefix with an underscore (`_`) to ignore:
- markdown-elements-demo-post.mdx
01:55:45 PM [content] Types generated 237ms
01:55:45 PM [build] output target: server
01:55:45 PM [build] deploy adapter: astro-sst/lambda
01:55:45 PM [build] Collecting build info...
01:55:45 PM [build] Completed in 259ms.
01:55:45 PM [build] Building server entrypoints...
[vite]: Rollup failed to resolve import "virtual:image-loader" from "/Users/luke/src/astro/EvonyTips_v2/node_modules/@astrojs/image/dist/lib/get-image.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
 error   [vite]: Rollup failed to resolve import "virtual:image-loader" from "/Users/luke/src/astro/EvonyTips_v2/node_modules/@astrojs/image/dist/lib/get-image.js".
  This is most likely unintended because it can break your application at runtime.
  If you do want to externalize this module explicitly add it to
  `build.rollupOptions.external`
Error: [vite]: Rollup failed to resolve import "virtual:image-loader" from "/Users/luke/src/astro/EvonyTips_v2/node_modules/@astrojs/image/dist/lib/get-image.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at onRollupWarning (file:///Users/luke/src/astro/EvonyTips_v2/node_modules/vite/dist/node/chunks/dep-c167897e.js:46353:19)
    at onwarn (file:///Users/luke/src/astro/EvonyTips_v2/node_modules/vite/dist/node/chunks/dep-c167897e.js:46123:13)
    at Object.onwarn (file:///Users/luke/src/astro/EvonyTips_v2/node_modules/rollup/dist/es/shared/node-entry.js:25097:13)
    at ModuleLoader.handleInvalidResolvedId (file:///Users/luke/src/astro/EvonyTips_v2/node_modules/rollup/dist/es/shared/node-entry.js:23779:26)
    at ModuleLoader.resolveDynamicImport (file:///Users/luke/src/astro/EvonyTips_v2/node_modules/rollup/dist/es/shared/node-entry.js:23835:58)
    at async file:///Users/luke/src/astro/EvonyTips_v2/node_modules/rollup/dist/es/shared/node-entry.js:23724:32
officium:EvonyTips_v2 luke$ 
```

I freshly cloned the repository yesterday and have only just started exploring Astro.   I tried to keep things fairly minimal to make sure I wasn't introducing the error by conflicting integrations.

```
officium:EvonyTips_v2 luke$ cat astro.config.mjs 
import { defineConfig } from "astro/config";
import aws from "astro-sst/lambda";

export default defineConfig({
  output: "server",
  adapter: aws(),
});
```

**Comment by lschierer** [comment]
note that I do not get this error with glob until after running the npx create-sst command, before that npm run build ran fine.
