### ISSUE TITLE
 Unable to Launch npm run dev after adding Vue Integration

### ISSUE THREAD

**Issue by mauriziocalarese** [onwidget/astrowind#265]
As mentioned in the subject, everything was working fine, but after adding Vue integration, I can no longer launch npm run dev without encountering errors.

The error message I'm seeing is as follows:

```$ npm run dev

> @onwidget/astrowind@1.0.0-beta.1 dev
> astro dev

Failed to load url @astrojs/partytown (resolved id: @astrojs/partytown) in C:/www/astrowind/astro.config.mjs. Does the file exist?
Failed to load url reading-time (resolved id: reading-time) in C:/www/astrowind/src/utils/frontmatter.mjs. Does the file exist?
Failed to load url mdast-util-to-string (resolved id: mdast-util-to-string) in C:/www/astrowind/src/utils/frontmatter.mjs. Does the file exist?
1:59:21 AM [vite] Error when evaluating SSR module C:\www/astrowind/astro.config.mjs: failed to import "@astrojs/tailwind"
|- Error: Cannot find module '@astrojs/tailwind' imported from 'C:/www/astrowind/astro.config.mjs'
    at nodeImport (file:///C:/www/astrowind/node_modules/vite/dist/node/chunks/dep-df561101.js:56010:25)
    at ssrImport (file:///C:/www/astrowind/node_modules/vite/dist/node/chunks/dep-df561101.js:55912:30)
    at eval (C:/www/astrowind/astro.config.mjs:7:37)
    at async instantiateModule (file:///C:/www/astrowind/node_modules/vite/dist/node/chunks/dep-df561101.js:55974:9)

[astro] Unable to load your Astro config

 error   Cannot find module '@astrojs/tailwind' imported from 'C:/www/astrowind/astro.config.mjs'
  File:
    C:\www/astrowind/node_modules/vite/dist/node/chunks/dep-df561101.js:56010:25
  Code:
    56009 |         if (!resolved) {
    > 56010 |             const err = new Error(`Cannot find module '${id}' imported from '${importer}'`);
            |                         ^
      56011 |             err.code = 'ERR_MODULE_NOT_FOUND';
      56012 |             throw err;
      56013 |         }
  Stacktrace:
Error: Cannot find module '@astrojs/tailwind' imported from 'C:/www/astrowind/astro.config.mjs'
    at nodeImport (file:///C:/www/astrowind/node_modules/vite/dist/node/chunks/dep-df561101.js:56010:25)
    at ssrImport (file:///C:/www/astrowind/node_modules/vite/dist/node/chunks/dep-df561101.js:55912:30)
    at eval (C:/www/astrowind/astro.config.mjs:7:37)
    at async instantiateModule (file:///C:/www/astrowind/node_modules/vite/dist/node/chunks/dep-df561101.js:55974:9)
```

```
// astro.config.mjs

import path from 'path';
import { fileURLToPath } from 'url';
import { defineConfig } from 'astro/config';
import sitemap from '@astrojs/sitemap';
import tailwind from '@astrojs/tailwind';
import mdx from '@astrojs/mdx';
import partytown from '@astrojs/partytown';
import compress from 'astro-compress';
import icon from 'astro-icon';
import tasks from './src/utils/tasks';
import { readingTimeRemarkPlugin } from './src/utils/frontmatter.mjs';
import { ANALYTICS, SITE } from './src/utils/config.ts';
import vue from "@astrojs/vue";
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const whenExternalScripts = (items = []) => ANALYTICS.vendors.googleAnalytics.id && ANALYTICS.vendors.googleAnalytics.partytown ? Array.isArray(items) ? items.map(item => item()) : [items()] : [];


// https://astro.build/config
export default defineConfig({
  site: SITE.site,
  base: SITE.base,
  trailingSlash: SITE.trailingSlash ? 'always' : 'never',
  output: 'static',
  image: {
    domains: ["firebasestorage.googleapis.com"],
    remotePatterns: [{
      protocol: "https"
    }]
  },
  integrations: [tailwind({
    applyBaseStyles: false
  }), sitemap(), mdx(), icon({
    include: {
      tabler: ['*'],
      'flat-color-icons': ['template', 'gallery', 'approval', 'document', 'advertising', 'currency-exchange', 'voice-presentation', 'business-contact', 'database']
    }
  }), ...whenExternalScripts(() => partytown({
    config: {
      forward: ['dataLayer.push']
    }
  })), tasks(), compress({
    CSS: true,
    HTML: {
      removeAttributeQuotes: false
    },
    Image: false,
    JavaScript: true,
    SVG: true,
    Logger: 1
  }), vue()],
  markdown: {
    remarkPlugins: [readingTimeRemarkPlugin]
  },
  vite: {
    resolve: {
      alias: {
        '~': path.resolve(__dirname, './src')
      }
    }
  }
});
```

``` 
// tsconfig.json

{
  "extends": "astro/tsconfigs/base",
  "compilerOptions": {
    "strictNullChecks": true,
    "allowJs": true,
    "baseUrl": ".",
    "paths": {
      "~/*": [
        "src/*"
      ]
    },
    "jsx": "preserve"
  }
}
```

If I remove the Vue integration, everything works fine again.

Please, how can I resolve this issue?

**Comment by prototypa** [comment]
Hi @mauriziocalarese 

I was reviewing the problem and when an integration such as vue or react is installed via:

```batch
npx astro add vue
```

For some reason, it must be a bug in *Astro*, the other dependencies are uninstalled. If you reinstall everything again it works:

```batch
npm i
```

Thanks

**Comment by mauriziocalarese** [comment]
I thought that was a local problem, but then I solved adding the integration manually.

Many thanks.
