### ISSUE TITLE
babel error on first install and run dev

### ISSUE THREAD

**Issue by joshuabenson** [onwidget/astrowind#289]
Hi

I'm running locally the latest main, and hitting a babel error right away. My node version is 20.6.0. Computer is a M1, OS Ventura 13.5.1 (22G90). This is the error after running `npm install` and then `npm run dev`:

astrowind 🤡 npm run dev

> @onwidget/astrowind@1.0.0-beta.6 dev
> astro dev

/Users/repos/ccs/astrowind/node_modules/@babel/core/lib/index.js:7
Object.defineProperty(exports, "File", {
       ^

TypeError: Cannot redefine property: File
    at Function.defineProperty (<anonymous>)
    at Object.<anonymous> (/Users/repos/ccs/astrowind/node_modules/@babel/core/lib/index.js:7:8)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/Users/repos/ccs/astrowind/node_modules/@babel/core/lib/config/helpers/config-api.js:16:14)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)

Node.js v20.6.0

My guess is incompatability with babel but I'm not sure which dependency is installing that version. I'll try manually installing different versions. Thanks!

**Comment by joshuabenson** [comment]
Noting I'm finding out that this is probably an issue with Node 20.6.0 if others are encountering this: https://github.com/microsoft/typespec/pull/2373

**Comment by prototypa** [comment]
Hello everyone, we know about the long delay. We were working on a complex project, we are back. In the discussion area we will present the new fixed and defined update schedule. Thanks for the patience.
