### ISSUE TITLE
Error: Cannot find module 'node_modules/@jridgewell/gen-mapping/dist/gen-mapping.umd.js'

### ISSUE THREAD

**Issue by akoskm** [onwidget/astrowind#563]
Hi 👋

I just copied the new dependencies from this project into https://github.com/innotekhq/innotek.dev-astro.

```
$ rm -rf node_modules
npm cache clean --force
npm install
```

all passed without errors, however on `npm start` I'm running into this error:

```
$ npm start

> @onwidget/astrowind@1.0.0-beta.6 start
> astro dev

8:37:51 AM [vite] Error when evaluating SSR module /Users/akoskm/Projects/innotek.dev-astro/astro.config.mjs: failed to import "@astrojs/tailwind"
|- Error: Cannot find module '/Users/akoskm/Projects/innotek.dev-astro/node_modules/@jridgewell/gen-mapping/dist/gen-mapping.umd.js'
    at createEsmNotFoundErr (node:internal/modules/cjs/loader:1262:15)
    at finalizeEsmResolution (node:internal/modules/cjs/loader:1250:15)
    at resolveExports (node:internal/modules/cjs/loader:634:14)
    at Module._findPath (node:internal/modules/cjs/loader:724:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1211:27)
    at Module._load (node:internal/modules/cjs/loader:1051:27)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/Users/akoskm/Projects/innotek.dev-astro/node_modules/sucrase/dist/computeSourceMap.js:1:92)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)

node:internal/process/promises:391
    triggerUncaughtException(err, true /* fromPromise */);
    ^

Error: Cannot find module '/Users/akoskm/Projects/innotek.dev-astro/node_modules/@jridgewell/gen-mapping/dist/gen-mapping.umd.js'
    at createEsmNotFoundErr (node:internal/modules/cjs/loader:1262:15)
    at finalizeEsmResolution (node:internal/modules/cjs/loader:1250:15)
    at resolveExports (node:internal/modules/cjs/loader:634:14)
    at Module._findPath (node:internal/modules/cjs/loader:724:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1211:27)
    at Module._load (node:internal/modules/cjs/loader:1051:27)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/Users/akoskm/Projects/innotek.dev-astro/node_modules/sucrase/dist/computeSourceMap.js:1:92)
    at Module._compile (node:internal/modules/cjs/loader:1469:14) {
  code: 'MODULE_NOT_FOUND',
  path: '/Users/akoskm/Projects/innotek.dev-astro/node_modules/@jridgewell/gen-mapping/package.json'
}

Node.js v20.18.0
```

Any ideas how to fix this?

**Comment by akoskm** [comment]
This is caused by a broken release in https://github.com/jridgewell/gen-mapping/issues/18.

This broke tailwind as well: https://github.com/tailwindlabs/tailwindcss/discussions/15363.

See my comment here https://github.com/tailwindlabs/tailwindcss/discussions/15363#discussioncomment-11529248.
