### ISSUE TITLE
Error clicking on blog link

### ISSUE THREAD

**Issue by frascu** [onwidget/astrowind#57]
In order to execute the project in my local environment, I executed the following commands:
```bash
npm install
npm run dev
```

The page **localhost:3000** works, but when I click on blog link I get this error:
```log
 error   Missing or empty required params property on getStaticPaths route
  Hint:
    See https://docs.astro.build/en/reference/api-reference/#getstaticpaths for more information on getStaticPaths.
  File:
    /home/francesco/MyApp/website/src/pages/[...tags]/[tag]/[...page].astro
  Stacktrace:
GetStaticPathsExpectedParams: Missing or empty required params property on getStaticPaths route
    at file:///home/francesco/MyApp/website/node_modules/astro/dist/core/routing/validation.js:42:13
    at Array.forEach (<anonymous>)
    at validateGetStaticPathsResult (file:///home/francesco/MyApp/website/node_modules/astro/dist/core/routing/validation.js:40:10)
    at callGetStaticPaths (file:///home/francesco/MyApp/website/node_modules/astro/dist/core/render/route-cache.js:28:5)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getParamsAndProps (file:///home/francesco/MyApp/website/node_modules/astro/dist/core/render/core.js:24:25)
    at async matchRoute (file:///home/francesco/MyApp/website/node_modules/astro/dist/vite-plugin-astro-server/route.js:27:31)
    at async run (file:///home/francesco/MyApp/website/node_modules/astro/dist/vite-plugin-astro-server/request.js:38:28)
    at async runWithErrorHandling (file:///home/francesco/MyApp/website/node_modules/astro/dist/vite-plugin-astro-server/controller.js:65:5)
    at async handleRequest (file:///home/francesco/MyApp/website/node_modules/astro/dist/vite-plugin-astro-server/request.js:34:3)
```

**Comment by ika-codes** [comment]
I'm having the same issue, looking forward to some kind of fix or idea how to resolve this error.

**Comment by jack-nui** [comment]
Can confirm I'm also having this issue.

**Comment by mhaidarhanif** [comment]
I tried solving it by downgrading `astro` to `1.6.5` for now. It works for a quick fix.

In `1.6.7`:

```sh
  🚀  astro  v1.6.7 started in 724ms

  ┃ Local    http://localhost:3000/
  ┃ Network  use --host to expose

07:47:15 AM [getStaticPaths] A getStaticPaths route pattern was matched, but no matching static path was found for requested path /sw.js.

Possible dynamic routes being matched: src/pages/[...tags]/[tag]/[...page].astro, src/pages/[...categories]/[category]/[...page].astro, src/pages/[...blog]/[slug].astro, src/pages/[...blog]/[...page].astro.
```

In `1.6.5`:

```sh
🚀  astro  v1.6.5 started in 827ms

  ┃ Local    http://localhost:3000/
  ┃ Network  use --host to expose

07:50:57 AM [getStaticPaths] Route pattern matched, but no matching static path found. (/sw.js)
07:50:57 AM [serve]    404                                   /sw.js
```

Screenshot on `/blog`:

![Screenshot](https://user-images.githubusercontent.com/235584/201554323-d12820cc-38fd-4add-8a5e-dbff0beb204e.png)

**Comment by makash** [comment]
Confirmed by Astro developers in their discord. Some error that will be fixed today

<img width="694" alt="image" src="https://user-images.githubusercontent.com/343204/201554678-366ca62a-4b7d-4691-a5cd-78300d26684c.png">

**Comment by frascu** [comment]
They committed https://github.com/withastro/astro/commit/f9104354b8a2c2457b9cd64405ddf8a832628e26.
I am waiting for 1.6.8 version.
